name: built_stream
description: This library is the runtime dependency.
version: 1.0.4
author: Dat Thanh Vo <datvt9312@gmail.com>
homepage: https://github.com/datvt9312/flutter_bloc/built_stream

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: 1.14.1
